export const countryCodes = [
    { code: '+376', name: 'Andorra' }, { code: '+971', name: 'United Arab Emirates' }, { code: '+93', name: 'Afghanistan' }, { code: '+1268', name: 'Antigua & Barbuda' },
    { code: '+1264', name: 'Anguilla' }, { code: '+355', name: 'Albania' }, { code: '+374', name: 'Armenia' }, { code: '+244', name: 'Angola' },
    { code: '+672', name: 'Antarctica' }, { code: '+54', name: 'Argentina' }, { code: '+1684', name: 'American Samoa' }, { code: '+43', name: 'Austria' },
    { code: '+61', name: 'Australia' }, { code: '+297', name: 'Aruba' }, { code: '+358', name: 'Åland Islands' }, { code: '+994', name: 'Azerbaijan' },
    { code: '+387', name: 'Bosnia & Herzegovina' }, { code: '+1246', name: 'Barbados' }, { code: '+880', name: 'Bangladesh' }, { code: '+32', name: 'Belgium' },
    { code: '+226', name: 'Burkina Faso' }, { code: '+359', name: 'Bulgaria' }, { code: '+973', name: 'Bahrain' }, { code: '+257', name: 'Burundi' },
    { code: '+229', name: 'Benin' }, { code: '+590', name: 'St. Barthélemy' }, { code: '+1441', name: 'Bermuda' }, { code: '+673', name: 'Brunei' },
    { code: '+591', name: 'Bolivia' }, { code: '+55', name: 'Brazil' }, { code: '+1242', name: 'Bahamas' }, { code: '+975', name: 'Bhutan' },
    { code: '+267', name: 'Botswana' }, { code: '+375', name: 'Belarus' }, { code: '+501', name: 'Belize' }, { code: '+1', name: 'Canada' },
    { code: '+61', name: 'Cocos (Keeling) Islands' }, { code: '+243', name: 'Congo - Kinshasa' }, { code: '+236', name: 'Central African Republic' }, { code: '+242', name: 'Congo - Brazzaville' },
    { code: '+41', name: 'Switzerland' }, { code: '+225', name: 'Côte d’Ivoire' }, { code: '+682', name: 'Cook Islands' }, { code: '+56', name: 'Chile' },
    { code: '+237', name: 'Cameroon' }, { code: '+86', name: 'China' }, { code: '+57', name: 'Colombia' }, { code: '+506', name: 'Costa Rica' },
    { code: '+53', name: 'Cuba' }, { code: '+238', name: 'Cape Verde' }, { code: '+61', name: 'Christmas Island' }, { code: '+357', name: 'Cyprus' },
    { code: '+420', name: 'Czechia' }, { code: '+49', name: 'Germany' }, { code: '+253', name: 'Djibouti' }, { code: '+45', name: 'Denmark' },
    { code: '+1767', name: 'Dominica' }, { code: '+1849', name: 'Dominican Republic' }, { code: '+213', name: 'Algeria' }, { code: '+593', name: 'Ecuador' },
    { code: '+372', name: 'Estonia' }, { code: '+20', name: 'Egypt' }, { code: '+291', name: 'Eritrea' }, { code: '+34', name: 'Spain' },
    { code: '+251', name: 'Ethiopia' }, { code: '+358', name: 'Finland' }, { code: '+679', name: 'Fiji' }, { code: '+500', name: 'Falkland Islands' },
    { code: '+691', name: 'Micronesia' }, { code: '+298', name: 'Faroe Islands' }, { code: '+33', name: 'France' }, { code: '+241', name: 'Gabon' },
    { code: '+44', name: 'United Kingdom' }, { code: '+1473', name: 'Grenada' }, { code: '+995', name: 'Georgia' }, { code: '+594', name: 'French Guiana' },
    { code: '+44', name: 'Guernsey' }, { code: '+233', name: 'Ghana' }, { code: '+350', name: 'Gibraltar' }, { code: '+299', name: 'Greenland' },
    { code: '+220', name: 'Gambia' }, { code: '+224', name: 'Guinea' }, { code: '+590', name: 'Guadeloupe' }, { code: '+240', name: 'Equatorial Guinea' },
    { code: '+30', name: 'Greece' }, { code: '+500', name: 'South Georgia & South Sandwich Islands' }, { code: '+502', name: 'Guatemala' }, { code: '+1671', name: 'Guam' },
    { code: '+245', name: 'Guinea-Bissau' }, { code: '+595', name: 'Guyana' }, { code: '+852', name: 'Hong Kong SAR China' }, { code: '+504', name: 'Honduras' },
    { code: '+385', name: 'Croatia' }, { code: '+509', name: 'Haiti' }, { code: '+36', name: 'Hungary' }, { code: '+62', name: 'Indonesia' },
    { code: '+353', name: 'Ireland' }, { code: '+972', name: 'Israel' }, { code: '+44', name: 'Isle of Man' }, { code: '+91', name: 'India' },
    { code: '+246', name: 'British Indian Ocean Territory' }, { code: '+964', name: 'Iraq' }, { code: '+98', name: 'Iran' }, { code: '+354', name: 'Iceland' },
    { code: '+39', name: 'Italy' }, { code: '+44', name: 'Jersey' }, { code: '+1876', name: 'Jamaica' }, { code: '+962', name: 'Jordan' },
    { code: '+81', name: 'Japan' }, { code: '+254', name: 'Kenya' }, { code: '+996', name: 'Kyrgyzstan' }, { code: '+855', name: 'Cambodia' },
    { code: '+686', name: 'Kiribati' }, { code: '+269', name: 'Comoros' }, { code: '+1869', name: 'St. Kitts & Nevis' }, { code: '+850', name: 'North Korea' },
    { code: '+82', name: 'South Korea' }, { code: '+965', name: 'Kuwait' }, { code: '+345', name: 'Cayman Islands' }, { code: '+77', name: 'Kazakhstan' },
    { code: '+856', name: 'Laos' }, { code: '+961', name: 'Lebanon' }, { code: '+1758', name: 'St. Lucia' }, { code: '+423', name: 'Liechtenstein' },
    { code: '+94', name: 'Sri Lanka' }, { code: '+231', name: 'Liberia' }, { code: '+266', name: 'Lesotho' }, { code: '+370', name: 'Lithuania' },
    { code: '+352', name: 'Luxembourg' }, { code: '+371', name: 'Latvia' }, { code: '+218', name: 'Libya' }, { code: '+212', name: 'Morocco' },
    { code: '+377', name: 'Monaco' }, { code: '+373', name: 'Moldova' }, { code: '+382', name: 'Montenegro' }, { code: '+590', name: 'St. Martin' },
    { code: '+261', name: 'Madagascar' }, { code: '+692', name: 'Marshall Islands' }, { code: '+389', name: 'North Macedonia' }, { code: '+223', name: 'Mali' },
    { code: '+95', name: 'Myanmar (Burma)' }, { code: '+976', name: 'Mongolia' }, { code: '+853', name: 'Macao SAR China' }, { code: '+1670', name: 'Northern Mariana Islands' },
    { code: '+596', name: 'Martinique' }, { code: '+222', name: 'Mauritania' }, { code: '+1664', name: 'Montserrat' }, { code: '+356', name: 'Malta' },
    { code: '+230', name: 'Mauritius' }, { code: '+960', name: 'Maldives' }, { code: '+265', name: 'Malawi' }, { code: '+52', name: 'Mexico' },
    { code: '+60', name: 'Malaysia' }, { code: '+258', name: 'Mozambique' }, { code: '+264', name: 'Namibia' }, { code: '+687', name: 'New Caledonia' },
    { code: '+227', name: 'Niger' }, { code: '+672', name: 'Norfolk Island' }, { code: '+234', name: 'Nigeria' }, { code: '+505', name: 'Nicaragua' },
    { code: '+31', name: 'Netherlands' }, { code: '+47', name: 'Norway' }, { code: '+977', name: 'Nepal' }, { code: '+674', name: 'Nauru' },
    { code: '+683', name: 'Niue' }, { code: '+64', name: 'New Zealand' }, { code: '+968', name: 'Oman' }, { code: '+507', name: 'Panama' },
    { code: '+51', name: 'Peru' }, { code: '+689', name: 'French Polynesia' }, { code: '+675', name: 'Papua New Guinea' }, { code: '+63', name: 'Philippines' },
    { code: '+92', name: 'Pakistan' }, { code: '+48', name: 'Poland' }, { code: '+508', name: 'St. Pierre & Miquelon' }, { code: '+872', name: 'Pitcairn Islands' },
    { code: '+1939', name: 'Puerto Rico' }, { code: '+970', name: 'Palestinian Territories' }, { code: '+351', name: 'Portugal' }, { code: '+680', name: 'Palau' },
    { code: '+595', name: 'Paraguay' }, { code: '+974', name: 'Qatar' }, { code: '+262', name: 'Réunion' }, { code: '+40', name: 'Romania' },
    { code: '+381', name: 'Serbia' }, { code: '+7', name: 'Russia' }, { code: '+250', name: 'Rwanda' }, { code: '+966', name: 'Saudi Arabia' },
    { code: '+677', name: 'Solomon Islands' }, { code: '+248', name: 'Seychelles' }, { code: '+249', name: 'Sudan' }, { code: '+46', name: 'Sweden' },
    { code: '+65', name: 'Singapore' }, { code: '+290', name: 'St. Helena' }, { code: '+386', name: 'Slovenia' }, { code: '+47', name: 'Svalbard & Jan Mayen' },
    { code: '+421', name: 'Slovakia' }, { code: '+232', name: 'Sierra Leone' }, { code: '+378', name: 'San Marino' }, { code: '+221', name: 'Senegal' },
    { code: '+252', name: 'Somalia' }, { code: '+597', name: 'Suriname' }, { code: '+211', name: 'South Sudan' }, { code: '+239', name: 'São Tomé & Príncipe' },
    { code: '+503', name: 'El Salvador' }, { code: '+963', name: 'Syria' }, { code: '+268', name: 'Eswatini' }, { code: '+1649', name: 'Turks & Caicos Islands' },
    { code: '+235', name: 'Chad' }, { code: '+228', name: 'Togo' }, { code: '+66', name: 'Thailand' }, { code: '+992', name: 'Tajikistan' },
    { code: '+690', name: 'Tokelau' }, { code: '+670', name: 'Timor-Leste' }, { code: '+993', name: 'Turkmenistan' }, { code: '+216', name: 'Tunisia' },
    { code: '+676', name: 'Tonga' }, { code: '+90', name: 'Turkey' }, { code: '+1868', name: 'Trinidad & Tobago' }, { code: '+688', name: 'Tuvalu' },
    { code: '+886', name: 'Taiwan' }, { code: '+255', name: 'Tanzania' }, { code: '+380', name: 'Ukraine' }, { code: '+256', name: 'Uganda' },
    { code: '+1', name: 'United States' }, { code: '+598', name: 'Uruguay' }, { code: '+998', name: 'Uzbekistan' }, { code: '+379', name: 'Vatican City' },
    { code: '+1784', name: 'St. Vincent & Grenadines' }, { code: '+58', name: 'Venezuela' }, { code: '+1284', name: 'British Virgin Islands' }, { code: '+1340', name: 'U.S. Virgin Islands' },
    { code: '+84', name: 'Vietnam' }, { code: '+678', name: 'Vanuatu' }, { code: '+681', name: 'Wallis & Futuna' }, { code: '+685', name: 'Samoa' },
    { code: '+967', name: 'Yemen' }, { code: '+262', name: 'Mayotte' }, { code: '+27', name: 'South Africa' }, { code: '+260', name: 'Zambia' },
    { code: '+263', name: 'Zimbabwe' }
  ];